LangString addOrReinstall ${LANG_ENGLISH} "Reinstall (keep matches, knowledge, and settings)"
LangString alreadyInstalled ${LANG_ENGLISH} "Hexglow is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "Hexglow ${VERSION} is already installed. Choose Reinstall to repair or replace program files, or Uninstall to remove only the application. Both options keep local data by default."
LangString appRunning ${LANG_ENGLISH} "Hexglow is running. Right-click its system tray icon and choose Quit Hexglow, then try again. Closing the main window keeps it running."
LangString appRunningOkKill ${LANG_ENGLISH} "Hexglow is running in the background. Quit from the tray first to save your match. OK will force-close it and continue; unsaved changes may be lost. Cancel returns to setup."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose Reinstall or Uninstall. Local data is kept unless you explicitly select the delete-data option."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose Reinstall or Uninstall. Both options keep local data by default."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Install over the current version (keep local data)"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "A downgrade cannot overwrite the installed version; uninstall the old program first (local data is kept by default)"
LangString failedToKillApp ${LANG_ENGLISH} "Hexglow could not be closed. Choose Quit Hexglow from the system tray, then try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing the required WebView2 runtime…"
LangString newerVersionInstalled ${LANG_ENGLISH} "A Hexglow version newer than ${VERSION} is installed. Continuing will install an older version. Choose Uninstall old program, then install this version. Match history, knowledge, and settings are kept by default."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An existing Hexglow installation was detected. Choose Uninstall old program, then install this version. Match history, knowledge, and settings are kept by default."
LangString silentDowngrades ${LANG_ENGLISH} "Silent mode cannot perform a downgrade. Use the graphical installer."
LangString unableToUninstall ${LANG_ENGLISH} "The previous uninstaller is missing or could not start. Close Hexglow and try again. Local data has not been deleted."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall application only (keep local data by default)"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall old program, then install this version (keep local data)"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 installation failed, so Hexglow cannot run. Check the network or install WebView2 first, then try again."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 download failed: $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 download completed"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading the required WebView2 runtime…"
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 installation failed with error code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installation completed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete matches, knowledge, and settings (cannot be undone)"
