LangString addOrReinstall ${LANG_SIMPCHINESE} "重新安装（保留对局、知识库与设置）"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "Hexglow 已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "Hexglow ${VERSION} 已安装。若要修复或覆盖程序文件，请选择“重新安装”；若只想移除程序，请选择“仅卸载”。两种操作默认都保留对局、知识库与设置。"
LangString appRunning ${LANG_SIMPCHINESE} "Hexglow 正在运行。请右键系统托盘图标，选择“退出 Hexglow”后重试；关闭主窗口不会退出后台。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "Hexglow 正在后台运行。建议先从系统托盘选择“退出 Hexglow”以保存对局。点击“确定”将强制关闭并继续，未保存内容可能丢失；点击“取消”返回。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择重新安装或仅卸载；除非明确勾选删除数据，否则本地数据会保留。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择重新安装或仅卸载；两种操作默认都保留本地数据。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "直接覆盖安装（保留本地数据）"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不能直接覆盖降级；请先卸载旧程序（默认保留数据）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法关闭 Hexglow。请从系统托盘选择“退出 Hexglow”后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装运行所需的 WebView2…"
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "检测到比 ${VERSION} 更新的 Hexglow。继续会安装较旧版本。建议选择“先卸载旧程序，再安装当前版本”；此操作默认保留对局、知识库与设置。"
LangString older ${LANG_SIMPCHINESE} "较旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "检测到已有 Hexglow。建议选择“先卸载旧程序，再安装当前版本”；此操作默认保留对局、知识库与设置。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "静默模式不能执行版本降级，请使用图形安装界面。"
LangString unableToUninstall ${LANG_SIMPCHINESE} "旧版卸载程序缺失或启动失败。请关闭 Hexglow 后重试；本地数据不会自动删除。"
LangString uninstallApp ${LANG_SIMPCHINESE} "仅卸载程序（默认保留本地数据）"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "先卸载旧程序，再安装当前版本（保留本地数据）"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "WebView2 安装失败，Hexglow 无法运行。请检查网络或先安装 WebView2 后重试。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "WebView2 下载失败：$0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 下载完成"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载运行所需的 WebView2…"
LangString webview2InstallError ${LANG_SIMPCHINESE} "WebView2 安装失败，错误代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装完成"
LangString deleteAppData ${LANG_SIMPCHINESE} "同时删除对局、知识库与设置（不可恢复）"
