fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            lol_augment_assistant_lib::backend::fetch_live,
            lol_augment_assistant_lib::backend::save_session,
            lol_augment_assistant_lib::backend::list_sessions,
            lol_augment_assistant_lib::backend::analyze,
            lol_augment_assistant_lib::backend::test_model,
            lol_augment_assistant_lib::decision::analyze_structured,
            lol_augment_assistant_lib::decision::test_provider,
            lol_augment_assistant_lib::knowledge::knowledge_list,
            lol_augment_assistant_lib::knowledge::knowledge_read,
            lol_augment_assistant_lib::knowledge::knowledge_validate,
            lol_augment_assistant_lib::knowledge::knowledge_save,
            lol_augment_assistant_lib::knowledge::knowledge_delete,
            lol_augment_assistant_lib::knowledge::knowledge_retrieve,
            lol_augment_assistant_lib::storage::storage_stats,
            lol_augment_assistant_lib::storage::delete_session,
            lol_augment_assistant_lib::storage::delete_analysis,
            lol_augment_assistant_lib::storage::maintain_storage,
            lol_augment_assistant_lib::storage::list_sessions_light,
            lol_augment_assistant_lib::storage::get_session,
            lol_augment_assistant_lib::storage::get_session_by_match,
            lol_augment_assistant_lib::collector::collector_snapshot,
            lol_augment_assistant_lib::collector::diagnostics
        ])
        .run(tauri::generate_context!())
        .unwrap()
}
