import {describe,it,expect} from 'vitest';
import {applySnapshot,newSession,type CollectorSnapshot} from './domain';
const live=(time:number)=>({gameData:{gameTime:time},activePlayer:{summonerName:'me'},allPlayers:[{summonerName:'me',championName:'Ahri',team:'ORDER'},{summonerName:'enemy',championName:'Garen',team:'CHAOS'}]});
const snapshot=(extra:Partial<CollectorSnapshot>={}):CollectorSnapshot=>({platformSupported:true,connection:'lcu-and-live',phase:'InProgress',gameId:'100',liveData:live(100),lcuSession:{gameData:{gameId:100}},endOfGame:null,result:null,observedAt:'2026-01-01T00:00:00Z',warnings:[],...extra});
describe('automatic lifecycle',()=>{
 it('creates a tracked snapshot when tool opens mid-game',()=>{const s=applySnapshot(newSession(),snapshot()).session;expect(s.matchId).toBe('100');expect(s.players).toHaveLength(2);expect(s.samples).toHaveLength(1);expect(s.ownPlayerId).toBe('me');});
 it('archives on exact new match id and clears old augments',()=>{const s=applySnapshot(newSession(),snapshot()).session;s.players[0].augments=['old'];const r=applySnapshot(s,snapshot({gameId:'101',liveData:live(20)}));expect(r.completed?.id).toBe(s.id);expect(r.session.id).not.toBe(s.id);expect(r.session.players[0].augments).toEqual([]);});
 it('never infers defeat from a disconnected API',()=>{const s=applySnapshot(newSession(),snapshot()).session;const r=applySnapshot(s,snapshot({connection:'disconnected',phase:'Unknown',gameId:null,liveData:null,lcuSession:null}));expect(r.session.result?.status).toBe('unknown');expect(r.session.endedAt).toBeUndefined();expect(r.session.matchId).toBe('100');});
 it('preserves automatic results through missing data and rejects mismatched results',()=>{let s=applySnapshot(newSession(),snapshot({result:{status:'win',source:'lcu-eog',gameId:'100',observedAt:'now'}})).session;s=applySnapshot(s,snapshot({result:{status:'loss',source:'lcu-eog',gameId:'999',observedAt:'later'}})).session;expect(s.result?.status).toBe('win');});
 it('does not create a fresh game repeatedly from a live-only GameEnd event',()=>{const snap=snapshot({gameId:null,lcuSession:null,connection:'live-only',result:{status:'win',source:'live-game-end',observedAt:'now'}});const first=applySnapshot(newSession(),snap).session;const next=applySnapshot(first,snap);expect(next.completed).toBeUndefined();expect(next.session.id).toBe(first.id);});
 it('does not carry a completed result into an unidentified later game even when time increases',()=>{const a=applySnapshot(newSession(),snapshot({result:{status:'win',source:'lcu-eog',gameId:'100',observedAt:'now'}})).session;const r=applySnapshot(a,snapshot({gameId:null,lcuSession:null,connection:'live-only',liveData:live(200)}));expect(r.completed?.id).toBe(a.id);expect(r.session.matchId).toBe('');expect(r.session.result?.status).toBe('unknown');});
 it('bounds samples and deduplicates stages',()=>{let s=newSession();for(let i=0;i<245;i++)s=applySnapshot(s,snapshot({observedAt:new Date(i*15000).toISOString(),liveData:live(i*15)})).session;expect(s.samples).toHaveLength(30);expect(s.timeline).toHaveLength(1);});
 it('records end phase without claiming a result',()=>{const s=applySnapshot(newSession(),snapshot({phase:'EndOfGame',liveData:null})).session;expect(s.endedAt).toBeDefined();expect(s.result?.status).toBe('unknown');});
});
