import {useState} from 'react';
import {phaseLabel,type Session} from './domain';
export function LiveOverview({session,busy,demo,ready,blockers,onRun,onSettings,onPatch,onResume,historical}:{session:Session;busy:boolean;demo:boolean;ready:boolean;blockers:string[];onRun:()=>void;onSettings:()=>void;onPatch:(p:Partial<Session>)=>void;onResume:()=>void;historical:boolean}){
 const [editing,setEditing]=useState(false);const own=session.players.find(p=>p.id===session.ownPlayerId),last=session.decisions.at(-1);const hasGame=!!session.players.length;const unknown=session.players.some(p=>!p.augmentsConfirmed);
 return <div className="live-simple"><section className="match-strip"><div className="hero-avatar">{own?.champion.slice(0,2)||'◇'}</div><div><span className="quiet-label">{demo?'模拟对局':historical?'历史对局':'当前对局'}</span><h1>{own?.champion||'等待进入对局'}</h1><p>{hasGame?phaseLabel(session.phase):'打开游戏即可，海萤会自动识别当前对局。'}</p></div>{historical&&<button onClick={onResume}>返回实时对局</button>}{hasGame&&<details className="lineup"><summary>双方阵容</summary>{['ORDER','CHAOS'].map(t=><p key={t}><b>{t===own?.team?'我方':'敌方'}</b> {session.players.filter(p=>p.team===t).map(p=>p.champion).join(' · ')}</p>)}</details>}</section>
 <section className="recommend-panel"><div className="recommend-heading"><h2>海克斯推荐</h2>{demo&&<span className="pill">演示结果</span>}{last&&<small>分析于 {new Date(last.at).toLocaleTimeString()}</small>}</div>
 {!hasGame?<div className="calm-empty"><span>✧</span><h3>先去享受游戏</h3><p>检测到对局后，这里会显示你的英雄与海克斯建议。</p><small>无需手动建立对局或保存快照</small></div>:<>{last?<><div className="simple-ranking">{last.result.ranking.map((r,i)=>{const c=(last.context as Session).candidates.find(c=>c.id===r.candidateId);return <article className={i===0?'hex-choice best':'hex-choice'} key={r.candidateId}><span className="quiet-label">{i===0?'优先考虑':`备选 ${i}`}</span><h3>{c?.name||r.candidateId}</h3><p>{r.reason}</p><details><summary>效果与注意事项</summary><p>{c?.description}</p>{r.risks.map((s,j)=><p key={j}>{s}</p>)}</details><button disabled={busy||last.chosenId===r.candidateId} onClick={()=>onPatch({decisions:session.decisions.map(d=>d===last?{...d,chosenId:r.candidateId}:d)})}>{last.chosenId===r.candidateId?'已记录选择':'我选了这个'}</button></article>;})}</div><details className="recommend-notes"><summary>查看分析说明与信息缺失</summary><p>{last.result.summary}</p>{last.result.missingInformation.map((s,i)=><p key={i}>{s}</p>)}<p>分数与排序不是胜率；这是上次分析时的建议，修改候选或局势后需要重新分析。</p></details></>:<div className="calm-empty"><span>◇</span><h3>{busy?'正在比较你的候选…':'等待候选海克斯'}</h3><p>当前版本尚不能自动读取选择界面。补充这次候选后，即可获取建议。</p></div>}
 {!demo&&<div className="next-action">{!ready?<><span>首次使用，请先连接你的模型。</span><button className="accent" onClick={onSettings}>前往设置</button></>:<><span>{busy?'正在分析，请稍候':blockers.length?blockers[0]:unknown?'将基于已知信息分析，未识别的海克斯不会当作没有。':'候选已就绪'}</span><button onClick={()=>setEditing(v=>!v)}>{editing?'收起候选':'补充 / 修改候选'}</button><button className="accent" disabled={busy||blockers.length>0} onClick={onRun}>{last?'重新分析':'获取建议'}</button></>}</div>}
 {editing&&<div className="candidate-entry"><p className="hint">仅需补充本轮候选，不要求逐一填写双方所有玩家。请填写真实效果，缺失信息不会自动编造。</p><div className="candidates">{session.candidates.map((c,i)=><div className="candidate" key={c.id}><label>候选 {i+1}<input disabled={busy} value={c.name} placeholder="海克斯名称" onChange={e=>onPatch({candidates:session.candidates.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/></label><textarea disabled={busy} value={c.description} aria-label={`候选${i+1}完整效果`} placeholder="效果与数值" onChange={e=>onPatch({candidates:session.candidates.map(x=>x.id===c.id?{...x,description:e.target.value}:x)})}/></div>)}</div></div>}</>}
 </section></div>;
}
