import React,{Children,isValidElement,useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
type Props=Omit<React.SelectHTMLAttributes<HTMLSelectElement>,'multiple'|'size'>;
export function Select({children,value,onChange,disabled,id,'aria-label':label,...rest}:Props){
 const options: {value:string;label:string;disabled:boolean}[]=[];
 Children.forEach(children,child=>{if(!isValidElement<React.OptionHTMLAttributes<HTMLOptionElement>>(child))return;const p=child.props;const text=Children.toArray(p.children).join('');options.push({value:String(p.value??text),label:text,disabled:!!p.disabled});});
 const uid=useId(),button=useRef<HTMLButtonElement>(null),popup=useRef<HTMLDivElement>(null);
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[focus,setFocus]=useState(0),[rect,setRect]=useState({left:0,top:0,width:0,maxHeight:300});
 const selected=options.find(o=>o.value===String(value??'')),visible=options.filter(o=>o.label.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 function close(){setOpen(false);setQuery('');}
 function choose(index:number){const item=visible[index];if(!item||item.disabled)return;onChange?.({target:{value:item.value},currentTarget:{value:item.value}} as React.ChangeEvent<HTMLSelectElement>);close();button.current?.focus();}
 function show(){if(disabled)return;const r=button.current!.getBoundingClientRect();const height=Math.min(360,window.innerHeight-24);const above=window.innerHeight-r.bottom<230&&r.top>230;setRect({left:Math.min(r.left,Math.max(12,window.innerWidth-r.width-12)),top:above?Math.max(12,r.top-height-8):r.bottom+8,width:r.width,maxHeight:above?Math.min(height,r.top-20):Math.max(120,Math.min(height,window.innerHeight-r.bottom-20))});setFocus(Math.max(0,options.findIndex(o=>o.value===String(value))));setOpen(true);}
 useEffect(()=>{if(!open)return;const click=(e:PointerEvent)=>{if(!button.current?.contains(e.target as Node)&&!popup.current?.contains(e.target as Node))close();};const scroll=(e:Event)=>{if(!popup.current?.contains(e.target as Node))close();};document.addEventListener('pointerdown',click);window.addEventListener('resize',close);window.addEventListener('scroll',scroll,true);return()=>{document.removeEventListener('pointerdown',click);window.removeEventListener('resize',close);window.removeEventListener('scroll',scroll,true);};},[open]);
 useEffect(()=>{popup.current?.querySelector('[data-focused="true"]')?.scrollIntoView({block:'nearest'});},[focus]);
 const keys=(e:React.KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close();button.current?.focus();}else if(e.key==='Tab'){close();}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();if(!open){show();return;}setFocus(i=>e.key==='Home'?0:e.key==='End'?visible.length-1:Math.max(0,Math.min(visible.length-1,i+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Enter'||(e.key===' '&&e.target===button.current)){e.preventDefault();if(open)choose(focus);else show();}};
 return <div className={`choice-control ${rest.className||''}`}><button type="button" id={id} ref={button} className="choice-trigger" disabled={disabled} role="combobox" aria-expanded={open} aria-controls={uid} aria-haspopup="listbox" aria-label={label||selected?.label||'选择选项'} aria-activedescendant={open?`${uid}-${focus}`:undefined} onKeyDown={keys} onClick={()=>open?close():show()}><span>{selected?.label||'请选择'}</span><svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path d="m4 6 4 4 4-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg></button>{open&&createPortal(<div ref={popup} className="choice-popup" onClick={e=>{e.stopPropagation();e.preventDefault();}} style={{position:'fixed',...rect}} onKeyDown={keys}>{options.length>7&&<input className="choice-search" autoFocus placeholder="搜索选项…" aria-label="搜索选项" value={query} onChange={e=>{setQuery(e.target.value);setFocus(0);}}/>}<div role="listbox" id={uid} aria-label={label||'可选项'}>{visible.length?visible.map((o,i)=><div role="option" id={`${uid}-${i}`} key={o.value} aria-selected={o.value===String(value)} aria-disabled={o.disabled} data-focused={i===focus} className={`choice-option ${o.value===String(value)?'selected':''} ${o.disabled?'disabled':''}`} onPointerMove={()=>setFocus(i)} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(i)}><span>{o.label}</span>{o.value===String(value)&&<b>✓</b>}</div>):<div className="choice-empty">没有匹配选项</div>}</div></div>,document.body)}</div>;
}
